spring:
  h2.console:
    enabled: true
    path: /db
  jpa:
    show-sql: true
    hibernate:
      #create-drop
      ddl-auto: update
  datasource:
    #salva em disco
    url: jdbc:h2:file:./data/app_db;DB_CLOSE_ON_EXIT=FALSE
    # salva em memoria
    #url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:

  rabbitmq:
    host: localhost
    port: 5672
    # heroku
    # port: 1883
    username: rabbitmq
    # heroku
    #username: gzxxrqrz:gzxxrqrz
    #password: 	AFEa2r4yYLTu3liQJJlRrzZ2lnmj5cjQ
    password: rabbitmq

queue:
  schedule:
    name: scheduleQueue

logging:
  file: data/logger.log
  level:
    org:
      springframework:
        web: debug
      hibernate: ERROR